config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  # Route to display the form for a new company
  get '/companies/new', to: 'companies#new', as: 'new_company'

  # Route for the companies index page
  get '/companies', to: 'companies#index'

  # Route to create a new company
  post '/companies', to: 'companies#create'

  # Route for showing a specific company
  get '/companies/:id', to: 'companies#show', as: 'company'

  # Route to display the form for editing an existing company
  get '/companies/:id/edit', to: 'companies#edit', as: 'edit_company'

  # Route to update an existing company
  patch '/companies/:id', to: 'companies#update'

  # Route to delete a company
  delete '/companies/:id', to: 'companies#destroy'

  # Employee routes
  get '/employees', to: 'employees#index'
  get '/employees/:id', to: 'employees#show'
  get '/companies/:company_id/employees', to: 'employees#index', as: 'company_employees'
  get '/companies/:company_id/employees/:id', to: 'employees#show', as: 'company_employee'
  get '/companies/:id/employees', to: 'employees#index', as: 'company_all_employees'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees
end
# # ###
# # # Path: app/models/company.rb
# # class Company < ApplicationRecord
# # end
# # ###
# #
# # # Path: app/controllers/companies_controller.rb
# # class CompaniesController < ApplicationController
# #   def index
# #     @companies = Company.all
# #   end
# # end
# #
# # # Path: app/views/companies/index.html.erb
# # <h1>Companies</h1>
# # <ul>
# #   <% @companies.each do |company| %>
# #     <li><%= company.name %></li>
# #   <% end %>
# # </ul>
# # ```
#
# # ###
# # # Path: app/models/company.rb
# # class Company < ApplicationRecord
# # end
# # ###
# #
# # # Path: app/controllers/companies_controller.rb
# # class CompaniesController < ApplicationController
# #   def index
# #     @companies = Company.all
# #   end
# # end
# #
# # # Path: app/views/companies/index.html.erb
# # <h1>Companies</h1>
# # <ul>
# #   <% @companies.each do |company| %>
# #     <li><%= company.name %></li>
# #   <% end %>
# # </ul>
# # ```
#
# # ###
# # # Path: app/models/company.rb
# # class Company < ApplicationRecord
# # end
# # ###
# #
# # # Path: app/controllers/companies_controller.rb
# # class CompaniesController < ApplicationController
# #   def index
# #     @companies = Company.all
# #   end
# # end
# #
# # # Path: app/views/companies/index.html.erb
# # <h1>Companies</h1>
# # <ul>
# #   <% @companies.each do |company| %>
# #     <li><%= company.name %></li>
# #   <% end %>
# # </ul>
# # ```
#
# # ###
# # # Path: app/models/company.rb
# # class Company < ApplicationRecord
# # end
# # ###
# #
# # # Path: app/controllers/companies_controller.rb
# # class CompaniesController < ApplicationController

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.order(created_at: :desc)
  end

  def show
    @company = Company.find(params[:id])
  end
end

def create
  @company = Company.new(company_params)
  if @company.save
    redirect_to companies_path
  else
    render :new
  end

  def company_params
    params.require(:company).permit(:name, :market_value, :active)
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to company_path(@company)
    else
      render :edit
    end
  end

end



# Path: app/views/companies/index.html.erb
# <h1>Companies</h1>
# <ul>
#   <% @companies.each do |company| %>
#     <li><%= company.name %></li>
#   <% end %>
# </ul>
# ```

# ###

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController


  def index
    if params[:company_id]
      @company = Company.find(params[:company_id])
      @employees = @company.employees
    else
      @employees = Employee.all
    end
  end



  def show
    @employee = Employee.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/companies/edit.html.erb
<%= form_with model: @company, local: true do |form| %>
  <!-- Form fields for company's attributes -->
  <%= form.submit "Update Company" %>
<% end %>

app/views/companies/index.html.erb
<h1>Companies</h1>

<% @companies.each do |company| %>
  <h3><%= company.name %></h3>
  <p>Market Value: <%= company.market_value %></p>
  <p>Active: <%= company.active %></p>
  <p>Created At: <%= company.created_at.strftime("%B %d, %Y") %></p>
<% end %>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<%= form_with model: @company, local: true do |form| %>
  <!-- Form fields for company's attributes -->
  <%= form.submit "Create Company" %>
<% end %>

app/views/companies/show.html.erb
<h1>Company Details</h1>

<%= link_to 'View Employees', company_employees_path(@company) %>
<%= link_to 'Update Company', edit_company_path(@company) %>
<%= link_to 'Delete Company', company_path(@company), method: :delete, data: { confirm: 'Are you sure?' } %>


<p>Name: <%= @company.name %></p>
<p>Market Value: <%= @company.market_value %></p>
<p>Active: <%= @company.active %></p>
<p>Created At: <%= @company.created_at %></p>
<h2>Employee Count: <%= @company.employees.count %></h2>

app/views/employees/index.html.erb
<h1>Employees</h1>

<% if @company %>
<h1><%= @company.name %> Employees</h1>
<% else %>
<h1>All Employees</h1>
<% end %>

<% @employees.each do |employee| %>
<h3><%= employee.name %></h3>
<p>Salary: <%= employee.salary %></p>
<p>Full Time: <%= employee.full_time %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= link_to "All Employees", "/employees" %>
    <%= link_to "All Companies", "/companies" %>
    <%= yield %>
  </body>
</html>